<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.1.4.169" />
    <PackageReference Include=" AutoMapper" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\YunKeEdu.Core\YunKeEdu.Core.csproj" />
    <ProjectReference Include="..\YunKeEdu.Infrastructure\YunKeEdu.Infrastructure.csproj" />
  </ItemGroup>
</Project>
